name: Deploy

on: push

env:
  CARTOHUB_AWS_ACCID: 222978711607
  CARTOHUB_AWS_ROLE_NAME: github-actions-cartohub-frontend-deploy
  CARTOHUB_AWS_FRONTEND_BUCKET_NAME: cartohub-staging-frontend-20230818002854164200000002

jobs:
  test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run build:staging

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      # use staging only on prototyping phase
      - run: npm run build:staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ env.CARTOHUB_AWS_ACCID }}:role/${{ env.CARTOHUB_AWS_ROLE_NAME }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ env.CARTOHUB_AWS_FRONTEND_BUCKET_NAME }} --exact-timestamps --delete
